services:
  oltp:
    image: postgres:latest
    container_name: bi-oltp
    environment:
      POSTGRES_USER: oltp
      POSTGRES_PASSWORD: oltp
      POSTGRES_DB: oltp
    ports:
      - "5432:5432"
    volumes:
      - ./database/oltp/1_oltp.sql:/docker-entrypoint-initdb.d/1_oltp.sql
      - ./database/oltp/2_oltp.sql:/docker-entrypoint-initdb.d/2_oltp.sql
    networks:
      - bi-network

  olap:
    image: postgres:latest
    container_name: bi-olap
    environment:
      POSTGRES_USER: olap
      POSTGRES_PASSWORD: olap
      POSTGRES_DB: olap
    ports:
      - "5433:5432"
    volumes:
      - ./database/olap/1_olap.sql:/docker-entrypoint-initdb.d/olap.sql
    networks:
      - bi-network

  metabase_db:
    image: postgres:latest
    container_name: metabase_db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: metabase
    ports:
      - "5435:5432"
    networks:
      - bi-network
  
  metabase:
    image: metabase/metabase
    container_name: bi-metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metabase_db
    ports:
      - "3000:3000"
    depends_on:
      - metabase_db
    networks:
      - bi-network

networks:
  bi-network:
    driver: bridge